FROM dunglas/frankenphp:1-php8.3-bookworm

WORKDIR /app

RUN install-php-extensions pdo_mysql curl

COPY . /app

ENV SERVER_NAME=:80
EXPOSE 80

CMD ["sh", "-c", "frankenphp php-server --root /app --listen :${PORT:-80}"]
