<?php
$pageTitle='Game Details'; require_once 'config/bootstrap.php'; $id=(int)($_GET['id']??0);
$s=$pdo->prepare('SELECT g.* FROM games g WHERE g.id=?');$s->execute([$id]);$game=$s->fetch(); if(!$game){http_response_code(404);die('Game not found.');}
$offers=$pdo->prepare('SELECT * FROM store_offers WHERE game_id=? AND is_available=1 ORDER BY price ASC, store_name ASC');$offers->execute([$id]);$offers=$offers->fetchAll();$best=$offers[0]??null;
$user=current_user($pdo);$played=false;if($user){ensure_personalization_table($pdo);$ps=$pdo->prepare('SELECT 1 FROM played_games WHERE user_id=? AND game_id=?');$ps->execute([$user['id'],$id]);$played=(bool)$ps->fetchColumn();}$wishlist=false;if($user){$w=$pdo->prepare('SELECT 1 FROM wishlists WHERE user_id=? AND game_id=?');$w->execute([$user['id'],$id]);$wishlist=(bool)$w->fetchColumn();}
$local=game_rating($pdo,$id);$rating=(float)($game['store_rating']??0);$externalReviews=external_review_sources($game,$offers);$steamSnap=steam_snapshot($game);$trailerSearch=youtube_search_url($game['title']);
$reviewsStmt=$pdo->prepare('SELECT r.rating,r.review,r.created_at,u.name FROM ratings r JOIN users u ON u.id=r.user_id WHERE r.game_id=? ORDER BY r.created_at DESC');$reviewsStmt->execute([$id]);$reviews=$reviewsStmt->fetchAll();
$tags=game_tags($game['genres']);
$similarGames=[];
if($tags){
    $similar=$pdo->prepare('SELECT * FROM games WHERE id<>? AND ('.implode(' OR ',array_fill(0,count($tags),'genres LIKE ?')).') ORDER BY featured DESC, store_rating DESC, title ASC LIMIT 6');
    $simParams=[$id];
    foreach($tags as $tag)$simParams[]='%'.$tag.'%';
    $similar->execute($simParams);
    $similarGames=$similar->fetchAll();
}
require 'partials/header.php';
?>
<div class="details"><div class="details-cover"><img id="gameCover" src="<?=e(asset_url((string)$game['cover_image']))?>" data-fallback="<?=e(site_url('images/game-placeholder.svg'))?>" alt="<?=e($game['title'])?>"><div class="cover-note">Image: store catalog artwork</div></div><div class="details-copy"><span class="eyebrow"><?=e($game['platforms'])?></span><h1><?=e($game['title'])?></h1><div class="details-rating" id="gameRating"><span>⭐ <?= $rating?number_format($rating,1):'—' ?>/100</span><span><?=number_format((int)$game['rating_count'])?> <?=e($game['rating_source']?:'store')?> ratings</span><?php if($best):?><span class="price">From <?=money((float)$best['price'])?></span><?php endif;?></div><p class="lead" id="gameDescription"><?=e($game['description'])?></p><div class="tag-row"><?php foreach($tags as $tag):?><span class="tag"><?=e($tag)?></span><?php endforeach;?><span class="tag"><?=e($game['age_rating'])?></span></div><div class="detail-actions"><?php if($user):?><form method="post" action="<?=e(site_url('wishlist-toggle.php'))?>"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="game_id" value="<?=$id?>"><button class="btn" type="submit"><?=$wishlist?'♥ Remove Wishlist':'♡ Add Wishlist'?></button></form><?php else:?><a class="btn" href="<?=e(site_url('login.php'))?>">Login to Wishlist</a><?php endif;?><?php if($user):?><form method="post" action="<?=e(site_url('played-toggle.php'))?>"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="game_id" value="<?=$id?>"><input type="hidden" name="redirect_to" value="<?=e(basename($_SERVER['PHP_SELF']).'?id='.$id)?>"><button class="btn btn-ghost" type="submit"><?=$played?'✓ Played':'Mark as Played'?></button></form><?php endif;?><a class="btn btn-ghost" href="#trailer">▶ Watch Trailer</a></div><div class="info-grid"><div><span>Developer</span><strong id="gameDeveloper"><?=e($game['developer'])?></strong></div><div><span>Publisher</span><strong id="gamePublisher"><?=e($game['publisher'])?></strong></div><div><span>Release</span><strong id="gameRelease"><?=e($game['release_date'])?></strong></div><div><span>Game mode</span><strong id="gameMode"><?=e($game['game_mode'])?></strong></div></div></div></div>
<?php if(stripos((string)$game['platforms'],'Mobile')!==false): ?>
<section class="mobile-install-section"><div class="section-head"><div><p class="eyebrow">Mobile download</p><h2>Get <?=e($game['title'])?></h2><p class="section-note">Official store listings only. GameMatch does not provide unofficial APK downloads.</p></div></div><div class="mobile-install-grid"><?php foreach($offers as $offer): if(in_array(strtolower((string)$offer['store_name']),['google play','app store'],true)): ?><a class="mobile-store-card" href="<?=e($offer['url'])?>" target="_blank" rel="noopener noreferrer"><span><?=store_icon($offer['store_name'])?></span><div><strong><?=e($offer['store_name'])?></strong><small>Official store listing ↗</small></div></a><?php endif; endforeach; ?></div></section>
<?php endif; ?>
<section class="buy-section" data-game-id="<?=$id?>"><div class="section-head"><div><p class="eyebrow">Compare stores</p><h2>Where should you buy?</h2></div></div><?php if(!empty($game['steam_app_id'])):?><div class="live-steam-card" data-steam-app-id="<?=e((string)$game['steam_app_id'])?>"><div><span class="eyebrow">Live Steam India price</span><strong class="live-steam-price">Checking Steam…</strong><small class="live-steam-note">Fetched live from Steam when this page loads.</small></div><a class="btn btn-ghost live-steam-link" href="https://store.steampowered.com/app/<?=e((string)$game['steam_app_id'])?>/" target="_blank" rel="noopener">Open Steam ↗</a></div><?php endif;?><div class="best-deal live-best-deal" hidden></div><?php if($best):?><div class="best-deal"><div><span>🏆 Cheapest listed offer</span><strong><?=store_icon($best['store_name'])?> <?=e($best['store_name'])?> — <?=money((float)$best['price'])?></strong><small>Prices shown are database snapshots and can change at the store.</small></div><a class="btn" href="<?=e($best['url'])?>" target="_blank" rel="noopener">Buy at cheapest store ↗</a></div><?php endif;?><div class="offers-grid live-offers-grid"><?php foreach($offers as $offer):?><div class="offer-card <?=$best && (string)$offer['store_name']===(string)$best['store_name'] && (string)($offer['external_id']??'')===(string)($best['external_id']??'') && (string)$offer['url']===(string)$best['url']?'cheapest':''?>"><div><span><?=store_icon($offer['store_name'])?> <?=e($offer['store_name'])?></span><small><?=e($offer['platform'])?></small></div><strong><?=money((float)$offer['price'])?></strong><?php if($offer['original_price']&&$offer['original_price']>$offer['price']):?><del><?=money((float)$offer['original_price'])?></del><?php endif;?><a class="btn btn-small btn-ghost" href="<?=e($offer['url'])?>" target="_blank" rel="noopener">Open Store ↗</a></div><?php endforeach;?></div></section>
<section id="trailer" class="media-section"><div class="section-head"><div><p class="eyebrow">Trailer</p><h2>Official trailer</h2></div></div><div class="trailer-panel"><div><span class="trailer-badge">🎥 Official trailer</span><h3><?=e($game['title'])?></h3><p>Open the official trailer search on YouTube. This avoids broken embed IDs and lets you choose the publisher/developer upload.</p></div><a class="btn" href="<?=e($trailerSearch)?>" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></div></section>
<section class="external-reviews"><div class="section-head"><div><p class="eyebrow">Store feedback</p><h2>Steam / Epic reviews</h2><p class="section-note">These are external store rating snapshots. Full review text remains on the source store.</p></div></div><div class="external-review-grid"><?php foreach($externalReviews as $src):?><article class="external-review-card"><div class="external-review-head"><span><?=e($src['icon'])?> <?=e($src['name'])?></span><?php if($src['name']==='Steam Community' && $steamSnap):?><strong><?=e((string)$steamSnap['percent'])?>%</strong><?php elseif($src['rating']!==null):?><strong><?=number_format((float)$src['rating'],1)?>/100</strong><?php endif;?></div><p><?php if($src['name']==='Steam Community' && $steamSnap):?><?=e($steamSnap['label'])?><?php else:?><?=e($src['label'])?><?php endif;?></p><?php if($src['name']==='Steam Community' && $steamSnap):?><small><?=number_format((int)$steamSnap['count'])?> English reviews in the verified snapshot</small><?php elseif($src['count']):?><small><?=number_format((int)$src['count'])?> ratings in catalog snapshot</small><?php endif;?><a class="text-link" href="<?=e($src['url'])?>" target="_blank" rel="noopener noreferrer">Read reviews ↗</a></article><?php endforeach;?></div></section>
<section class="reviews-section"><div class="section-head"><div><p class="eyebrow">Community</p><h2>Ratings & reviews</h2></div></div><?php if($user):?><form class="review-form" method="post" action="<?=e(site_url('rating.php'))?>"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="game_id" value="<?=$id?>"><div class="field"><label>Your rating</label><select name="rating" required><option value="">Choose</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>"><?=$i?> - <?=$i===5?'Excellent':($i===4?'Great':($i===3?'Good':($i===2?'Fair':'Poor')))?></option><?php endfor;?></select></div><div class="field wide"><label>Review</label><textarea name="review" maxlength="1000" placeholder="What did you think?"></textarea></div><button class="btn" type="submit">Submit Rating</button></form><?php else:?><div class="login-note"><strong>Join the GameMatch community</strong><p>Log in to leave a rating and review, or create a free account.</p><div class="detail-actions"><a class="btn btn-small" href="<?=e(site_url('login.php'))?>">Login</a><a class="btn btn-small btn-ghost" href="<?=e(site_url('register.php'))?>">Register</a></div></div><?php endif;?><div class="reviews"><?php foreach($reviews as $review):?><article class="review"><div class="review-head"><strong><?=e($review['name'])?></strong><span>⭐ <?=e((string)$review['rating'])?>/5</span></div><?php if($review['review']):?><p><?=e($review['review'])?></p><?php endif;?><small><?=e(date('d M Y',strtotime($review['created_at'])))?></small></article><?php endforeach;?><?php if(!$reviews):?><div class="empty compact"><p>No GameMatch reviews yet.</p></div><?php endif;?></div></section>
<?php if($similarGames):?><section class="section-head"><div><p class="eyebrow">Because you liked this</p><h2>More like this</h2></div></section><div class="game-grid similar-grid"><?php foreach($similarGames as $g):$bo=best_offer($pdo,(int)$g['id']);?><article class="game-card"><a href="game-details.php?id=<?=(int)$g['id']?>"><img src="<?=e(asset_url((string)$g['cover_image']))?>" data-fallback="<?=e(site_url('images/covers/cover'.str_pad((string)$g['id'],2,'0',STR_PAD_LEFT).'.svg'))?>" alt="<?=e($g['title'])?>" loading="lazy"></a><div class="game-card-body"><div class="card-top"><span class="badge"><?=e(first_tag($g['platforms'],'—'))?></span><span class="rating">⭐ <?=number_format((float)$g['store_rating'],1)?></span></div><h3><a href="game-details.php?id=<?=(int)$g['id']?>"><?=e($g['title'])?></a></h3><p><?=e($g['genres'])?></p><div class="card-bottom"><strong><?=$bo?money((float)$bo['price']):'Price unavailable'?></strong><a href="game-details.php?id=<?=(int)$g['id']?>">View →</a></div></div></article><?php endforeach;?></div><?php endif;?>
<script>
(async function(){
  const id=<?=json_encode($id)?>;
  try{
    const r=await fetch('api/game-metadata.php?id='+encodeURIComponent(id),{headers:{'Accept':'application/json'}});
    const d=await r.json();
    if(!d.ok||!d.found)return;
    const set=(id,v)=>{const e=document.getElementById(id);if(e&&v)e.textContent=v;};
    if(d.cover_image){const img=document.getElementById('gameCover');if(img)img.src=d.cover_image;}
    set('gameDeveloper',d.developer);set('gamePublisher',d.publisher);set('gameRelease',d.release_date);set('gameMode',d.game_mode);
    const desc=document.getElementById('gameDescription');if(desc&&d.description)desc.textContent=d.description;
    const rating=document.getElementById('gameRating');if(rating&&d.rating!==null){rating.innerHTML='<span>⭐ '+Number(d.rating).toFixed(1)+'/100</span><span>'+Number(d.rating_count||0).toLocaleString('en-IN')+' Steam ratings</span>';}
  }catch(e){}
})();
</script>
<?php require 'partials/footer.php'; ?>
