-- GameMatch 3.1 safe catalog/bootstrap migration.
-- Does not DROP, TRUNCATE, or delete users, wishlists, ratings, games, or offers.
-- It adds the 50 cross-platform baseline titles already shipped with GameMatch.
-- Steam sync then enriches/updates Steam-linked rows and live pricing.


CREATE TABLE IF NOT EXISTS gamematch_catalog_bootstrap_31 (title VARCHAR(150) NOT NULL, slug VARCHAR(170) NOT NULL, developer VARCHAR(150), publisher VARCHAR(150), release_date DATE, platforms VARCHAR(255) NOT NULL, genres VARCHAR(255) NOT NULL, game_mode VARCHAR(100) NOT NULL, age_rating VARCHAR(20) DEFAULT 'T', price DECIMAL(10,2) NOT NULL DEFAULT 0, description TEXT NOT NULL, cover_image VARCHAR(500) NOT NULL, trailer_url VARCHAR(500), steam_app_id INT NULL, store_rating DECIMAL(4,1) NULL, rating_count BIGINT DEFAULT 0, rating_source VARCHAR(50), featured TINYINT(1) DEFAULT 0);

DELETE FROM gamematch_catalog_bootstrap_31;

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Elden Ring','elden-ring','FromSoftware','Bandai Namco Entertainment','2022-02-25','PC, PlayStation, Xbox','Action, RPG, Adventure','Single-player, Multiplayer','M',3999,'Explore the Lands Between in a large open-world action RPG with challenging combat, character builds, dungeons and online co-op.','https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg','https://www.youtube.com/embed?listType=search&list=Elden+Ring+Official+Trailer',1245620,95.0,900000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Cyberpunk 2077','cyberpunk-2077','CD PROJEKT RED','CD PROJEKT RED','2020-12-10','PC, PlayStation, Xbox','Action, RPG, Open World','Single-player','M',2999,'A story-driven open-world RPG set in Night City with branching quests, vehicles, combat and character customization.','https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg','https://www.youtube.com/embed?listType=search&list=Cyberpunk+2077+Official+Trailer',1091500,88.0,700000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('The Witcher 3: Wild Hunt','the-witcher-3','CD PROJEKT RED','CD PROJEKT RED','2015-05-18','PC, PlayStation, Xbox, Nintendo Switch','RPG, Adventure, Open World','Single-player','M',999,'A story-rich fantasy RPG with a huge open world, monster hunting, political choices and memorable quests.','https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg','https://www.youtube.com/embed?listType=search&list=The+Witcher+3+Official+Trailer',292030,96.0,800000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Red Dead Redemption 2','red-dead-redemption-2','Rockstar Games','Rockstar Games','2019-12-05','PC, PlayStation, Xbox','Action, Adventure, Open World','Single-player, Multiplayer','M',2999,'An epic western adventure featuring a vast open world, cinematic storytelling, wildlife, exploration and Red Dead Online.','https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg','https://www.youtube.com/embed?listType=search&list=Red+Dead+Redemption+2+Official+Trailer',1174180,94.0,600000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Grand Theft Auto V','grand-theft-auto-v','Rockstar North','Rockstar Games','2015-04-14','PC, PlayStation, Xbox','Action, Adventure, Open World','Single-player, Multiplayer','M',1499,'A huge open-world crime adventure with story mode and GTA Online.','https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg','https://www.youtube.com/embed?listType=search&list=GTA+V+Official+Trailer',271590,89.0,1700000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Baldur’s Gate 3','baldurs-gate-3','Larian Studios','Larian Studios','2023-08-03','PC, PlayStation, Xbox','RPG, Adventure, Strategy','Single-player, Multiplayer','M',3499,'A party-based RPG with deep choices, turn-based combat, branching stories and cooperative adventure.','https://cdn.cloudflare.steamstatic.com/steam/apps/1086940/header.jpg','https://www.youtube.com/embed?listType=search&list=Baldurs+Gate+3+Official+Trailer',1086940,96.0,400000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Hades','hades','Supergiant Games','Supergiant Games','2020-09-17','PC, PlayStation, Xbox, Nintendo Switch','Action, RPG, Roguelike','Single-player','T',1399,'Battle out of the Underworld in a fast roguelike action game with story progression and build variety.','https://cdn.cloudflare.steamstatic.com/steam/apps/1145360/header.jpg','https://www.youtube.com/embed?listType=search&list=Hades+Official+Trailer',1145360,98.0,250000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Hogwarts Legacy','hogwarts-legacy','Avalanche Software','Warner Bros. Games','2023-02-10','PC, PlayStation, Xbox, Nintendo Switch','Action, Adventure, RPG','Single-player','T',2499,'Explore Hogwarts and its surrounding world, learn spells, solve mysteries and develop your wizarding character.','https://cdn.cloudflare.steamstatic.com/steam/apps/990080/header.jpg','https://www.youtube.com/embed?listType=search&list=Hogwarts+Legacy+Official+Trailer',990080,91.0,200000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Helldivers 2','helldivers-2','Arrowhead Game Studios','PlayStation Publishing LLC','2024-02-08','PC, PlayStation','Action, Shooter, Co-op','Multiplayer','M',2999,'Team up in chaotic four-player missions where coordination, friendly fire and escalating enemy threats matter.','https://cdn.cloudflare.steamstatic.com/steam/apps/553850/header.jpg','https://www.youtube.com/embed?listType=search&list=Helldivers+2+Official+Trailer',553850,92.0,350000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Counter-Strike 2','counter-strike-2','Valve','Valve','2023-09-27','PC','FPS, Action, Multiplayer','Multiplayer','M',0,'Competitive tactical FPS with classic bomb-defusal gameplay, matchmaking and a large esports community.','https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg','https://www.youtube.com/embed?listType=search&list=Counter+Strike+2+Official+Trailer',730,88.0,8500000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Dota 2','dota-2','Valve','Valve','2013-07-09','PC','MOBA, Strategy, Multiplayer','Multiplayer','T',0,'Free-to-play competitive MOBA with deep hero abilities, strategy and team play.','https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg','https://www.youtube.com/embed?listType=search&list=Dota+2+Official+Trailer',570,90.0,2000000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('PUBG: BATTLEGROUNDS','pubg-battlegrounds','PUBG Corporation','KRAFTON','2017-12-21','PC, PlayStation, Xbox, Mobile','Battle Royale, Shooter, Multiplayer','Multiplayer','T',0,'Battle royale shooter focused on survival, looting, positioning and last-player-standing matches.','https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg','https://www.youtube.com/embed?listType=search&list=PUBG+Official+Trailer',578080,85.0,2500000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Apex Legends','apex-legends','Respawn Entertainment','Electronic Arts','2020-11-04','PC, PlayStation, Xbox, Nintendo Switch','FPS, Battle Royale, Multiplayer','Multiplayer','T',0,'Free-to-play hero battle royale with squad-based combat, unique abilities and fast movement.','https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg','https://www.youtube.com/embed?listType=search&list=Apex+Legends+Official+Trailer',1172470,88.0,800000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Forza Horizon 5','forza-horizon-5','Playground Games','Xbox Game Studios','2021-11-09','PC, Xbox','Racing, Open World, Adventure','Single-player, Multiplayer','E10+',3499,'Open-world festival racing across Mexico with hundreds of cars, events, customization and online play.','https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg','https://www.youtube.com/embed?listType=search&list=Forza+Horizon+5+Official+Trailer',1551360,90.0,150000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Halo Infinite','halo-infinite','343 Industries','Xbox Game Studios','2021-11-15','PC, Xbox','FPS, Action, Multiplayer','Single-player, Multiplayer','T',0,'Halo multiplayer and campaign experience with arena combat, vehicles and a sci-fi campaign.','https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg','https://www.youtube.com/embed?listType=search&list=Halo+Infinite+Official+Trailer',1240440,78.0,250000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Sea of Thieves','sea-of-thieves','Rare','Xbox Game Studios','2018-03-20','PC, Xbox, PlayStation','Adventure, Action, Multiplayer','Multiplayer','T',2499,'A shared pirate adventure about sailing, treasure hunting, naval combat and emergent encounters.','https://cdn.cloudflare.steamstatic.com/steam/apps/1172620/header.jpg','https://www.youtube.com/embed?listType=search&list=Sea+of+Thieves+Official+Trailer',1172620,90.0,300000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Starfield','starfield','Bethesda Game Studios','Bethesda Softworks','2023-09-06','PC, Xbox','RPG, Open World, Sci-Fi','Single-player','M',3999,'Explore planets, build ships, join factions and shape your own spacefaring story.','https://cdn.cloudflare.steamstatic.com/steam/apps/1716740/header.jpg','https://www.youtube.com/embed?listType=search&list=Starfield+Official+Trailer',1716740,68.0,120000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Resident Evil 4','resident-evil-4','CAPCOM','CAPCOM','2023-03-24','PC, PlayStation, Xbox','Horror, Action, Survival Horror','Single-player','M',2999,'A modern survival-horror remake with tense combat, exploration, puzzles and cinematic set pieces.','https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg','https://www.youtube.com/embed?listType=search&list=Resident+Evil+4+Official+Trailer',2050650,97.0,130000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Dead by Daylight','dead-by-daylight','Behaviour Interactive','Behaviour Interactive','2016-06-14','PC, PlayStation, Xbox, Nintendo Switch','Horror, Multiplayer','Multiplayer','M',799,'Asymmetric multiplayer horror where one player hunts four survivors trying to escape.','https://cdn.cloudflare.steamstatic.com/steam/apps/381210/header.jpg','https://www.youtube.com/embed?listType=search&list=Dead+by+Daylight+Official+Trailer',381210,80.0,550000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Phasmophobia','phasmophobia','Kinetic Games','Kinetic Games','2020-09-18','PC, PlayStation, Xbox','Horror, Co-op, Investigation','Multiplayer','T',699,'Co-op paranormal investigation where teams identify ghosts using equipment and evidence.','https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg','https://www.youtube.com/embed?listType=search&list=Phasmophobia+Official+Trailer',739630,96.0,400000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('The Outlast Trials','the-outlast-trials','Red Barrels','Red Barrels','2024-03-05','PC, PlayStation, Xbox','Horror, Co-op, Survival','Multiplayer','M',1499,'Survive terrifying experiments alone or with a team in this cooperative horror experience.','https://cdn.cloudflare.steamstatic.com/steam/apps/1304930/header.jpg','https://www.youtube.com/embed?listType=search&list=The+Outlast+Trials+Official+Trailer',1304930,89.0,100000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('God of War Ragnarök','god-of-war-ragnarok','Santa Monica Studio','PlayStation Publishing LLC','2022-11-09','PC, PlayStation','Action, Adventure','Single-player','M',3999,'Kratos and Atreus journey through Norse realms in a cinematic action adventure.','https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg','https://www.youtube.com/embed?listType=search&list=God+of+War+Ragnarok+Official+Trailer',2322010,94.0,100000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Marvel’s Spider-Man Remastered','spider-man-remastered','Insomniac Games','PlayStation Publishing LLC','2022-08-12','PC, PlayStation','Action, Adventure, Open World','Single-player','T',3999,'Swing through New York, fight villains and experience a cinematic superhero story.','https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg','https://www.youtube.com/embed?listType=search&list=Spider-Man+Remastered+Official+Trailer',1817070,96.0,80000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Horizon Forbidden West Complete Edition','horizon-forbidden-west','Guerrilla','PlayStation Publishing LLC','2024-03-21','PC, PlayStation','Action, Adventure, RPG, Open World','Single-player','T',3999,'Explore a beautiful post-apocalyptic world, hunt machines and uncover the secrets of Aloy’s journey.','https://cdn.cloudflare.steamstatic.com/steam/apps/2420110/header.jpg','https://www.youtube.com/embed?listType=search&list=Horizon+Forbidden+West+Official+Trailer',2420110,90.0,50000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Ghost of Tsushima DIRECTOR’S CUT','ghost-of-tsushima','Sucker Punch Productions','PlayStation Publishing LLC','2024-05-16','PC, PlayStation','Action, Adventure, Open World','Single-player, Multiplayer','M',3999,'Explore feudal Japan, master samurai combat and experience the Director’s Cut story and Iki Island.','https://cdn.cloudflare.steamstatic.com/steam/apps/2215430/header.jpg','https://www.youtube.com/embed?listType=search&list=Ghost+of+Tsushima+Official+Trailer',2215430,95.0,60000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Gran Turismo 7','gran-turismo-7','Polyphony Digital','Sony Interactive Entertainment','2022-03-04','PlayStation','Racing, Simulation','Single-player, Multiplayer','E',4499,'Realistic racing simulation with a large car roster, detailed circuits and competitive online racing.','https://image.api.playstation.com/vulcan/ap/rnd/202109/1320/0xJ0cZ2M7XQ9Y4v4v0V2kV0w.png','https://www.youtube.com/embed?listType=search&list=Gran+Turismo+7+Official+Trailer',NULL,NULL,0,'PlayStation',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('F1 25','f1-25','Codemasters','Electronic Arts','2025-05-30','PC, PlayStation, Xbox','Racing, Simulation, Sports','Single-player, Multiplayer','E',3999,'Official Formula 1 racing with licensed teams, circuits, career modes and online competition.','https://cdn.cloudflare.steamstatic.com/steam/apps/3059520/header.jpg','https://www.youtube.com/embed?listType=search&list=F1+25+Official+Trailer',3059520,82.0,10000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Rocket League','rocket-league','Psyonix','Epic Games','2015-07-07','PC, PlayStation, Xbox, Nintendo Switch','Sports, Racing, Multiplayer','Multiplayer','E',0,'Fast competitive car football with ranked matches, custom vehicles and cross-platform play.','https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg','https://www.youtube.com/embed?listType=search&list=Rocket+League+Official+Trailer',252950,92.0,700000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Fortnite','fortnite','Epic Games','Epic Games','2017-07-25','PC, PlayStation, Xbox, Mobile','Battle Royale, Action, Multiplayer','Multiplayer','T',0,'Free-to-play battle royale and creator platform with building, events and multiple game modes.','https://cdn2.unrealengine.com/fortnite-og-1920x1080-5d8f0f2f1f7b.jpg','https://www.youtube.com/embed?listType=search&list=Fortnite+Official+Trailer',NULL,NULL,0,'Epic Games',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Alan Wake 2','alan-wake-2','Remedy Entertainment','Epic Games Publishing','2023-10-27','PC, PlayStation, Xbox','Horror, Action, Adventure','Single-player','M',2499,'A psychological survival-horror mystery told through two connected protagonists and shifting realities.','https://cdn.cloudflare.steamstatic.com/steam/apps/1087100/header.jpg','https://www.youtube.com/embed?listType=search&list=Alan+Wake+2+Official+Trailer',1087100,94.0,30000,'Steam',1);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Control Ultimate Edition','control','Remedy Entertainment','505 Games','2020-08-27','PC, PlayStation, Xbox','Action, Adventure, Sci-Fi','Single-player','M',999,'A supernatural action adventure with telekinetic combat, shifting architecture and a mysterious government agency.','https://cdn.cloudflare.steamstatic.com/steam/apps/870780/header.jpg','https://www.youtube.com/embed?listType=search&list=Control+Official+Trailer',870780,90.0,150000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Death Stranding Director’s Cut','death-stranding','Kojima Productions','505 Games','2022-03-30','PC, PlayStation','Adventure, Action, Open World','Single-player','M',2499,'Reconnect a fractured world through traversal, delivery systems, stealth and a cinematic story.','https://cdn.cloudflare.steamstatic.com/steam/apps/1850570/header.jpg','https://www.youtube.com/embed?listType=search&list=Death+Stranding+Directors+Cut+Official+Trailer',1850570,93.0,50000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Sekiro: Shadows Die Twice','sekiro','FromSoftware','Activision','2019-03-21','PC, PlayStation, Xbox','Action, RPG, Soulslike','Single-player','M',2999,'Master precise sword combat, stealth and resurrection mechanics in a challenging Sengoku-era adventure.','https://cdn.cloudflare.steamstatic.com/steam/apps/814380/header.jpg','https://www.youtube.com/embed?listType=search&list=Sekiro+Official+Trailer',814380,95.0,250000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Dark Souls III','dark-souls-iii','FromSoftware','Bandai Namco Entertainment','2016-04-12','PC, PlayStation, Xbox','Action, RPG, Soulslike','Single-player, Multiplayer','M',2999,'A dark fantasy action RPG with demanding combat, interconnected areas and online summoning.','https://cdn.cloudflare.steamstatic.com/steam/apps/374320/header.jpg','https://www.youtube.com/embed?listType=search&list=Dark+Souls+3+Official+Trailer',374320,94.0,300000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Monster Hunter: World','monster-hunter-world','CAPCOM','CAPCOM','2018-08-09','PC, PlayStation, Xbox','Action, RPG, Co-op','Single-player, Multiplayer','T',1999,'Hunt giant monsters, craft gear and team up with other hunters in a living ecosystem.','https://cdn.cloudflare.steamstatic.com/steam/apps/582010/header.jpg','https://www.youtube.com/embed?listType=search&list=Monster+Hunter+World+Official+Trailer',582010,88.0,300000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Bioshock Infinite','bioshock-infinite','Irrational Games','2K','2013-03-26','PC, PlayStation, Xbox','FPS, Action, Adventure','Single-player','M',699,'Travel to the floating city of Columbia in a story-heavy first-person action adventure.','https://cdn.cloudflare.steamstatic.com/steam/apps/8870/header.jpg','https://www.youtube.com/embed?listType=search&list=Bioshock+Infinite+Official+Trailer',8870,94.0,150000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Portal 2','portal-2','Valve','Valve','2011-04-18','PC, PlayStation, Xbox','Puzzle, Adventure, Co-op','Single-player, Multiplayer','E10+',499,'Solve physics-based puzzles using portals in a celebrated single-player and cooperative campaign.','https://cdn.cloudflare.steamstatic.com/steam/apps/620/header.jpg','https://www.youtube.com/embed?listType=search&list=Portal+2+Official+Trailer',620,98.0,400000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Terraria','terraria','Re-Logic','Re-Logic','2011-05-16','PC, PlayStation, Xbox, Mobile','Adventure, Sandbox, RPG','Single-player, Multiplayer','T',499,'Dig, build, fight bosses and explore a procedurally generated sandbox world with friends.','https://cdn.cloudflare.steamstatic.com/steam/apps/105600/header.jpg','https://www.youtube.com/embed?listType=search&list=Terraria+Official+Trailer',105600,97.0,900000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Stardew Valley','stardew-valley','ConcernedApe','ConcernedApe','2016-02-26','PC, PlayStation, Xbox, Mobile','Simulation, RPG, Farming','Single-player, Multiplayer','E10+',699,'Build a farm, meet villagers, explore caves and create a relaxed life in Stardew Valley.','https://cdn.cloudflare.steamstatic.com/steam/apps/413150/header.jpg','https://www.youtube.com/embed?listType=search&list=Stardew+Valley+Official+Trailer',413150,98.0,600000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Palworld','palworld','Pocketpair','Pocketpair','2024-01-19','PC, Xbox','Survival, Action, Adventure','Single-player, Multiplayer','T',1999,'Collect mysterious creatures, build bases, craft equipment and survive a large open world.','https://cdn.cloudflare.steamstatic.com/steam/apps/1623730/header.jpg','https://www.youtube.com/embed?listType=search&list=Palworld+Official+Trailer',1623730,91.0,300000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Brotato','brotato','Blobfish','Blobfish','2022-09-27','PC, PlayStation, Xbox, Mobile','Action, Roguelike','Single-player','T',499,'A fast top-down roguelike shooter where a potato fights waves of aliens using many weapon builds.','https://cdn.cloudflare.steamstatic.com/steam/apps/1942280/header.jpg','https://www.youtube.com/embed?listType=search&list=Brotato+Official+Trailer',1942280,96.0,100000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Vampire Survivors','vampire-survivors','poncle','poncle','2022-10-20','PC, PlayStation, Xbox, Mobile','Action, Roguelike, Casual','Single-player, Multiplayer','T',249,'Survive endless enemy waves, collect upgrades and create powerful automated builds.','https://cdn.cloudflare.steamstatic.com/steam/apps/1794680/header.jpg','https://www.youtube.com/embed?listType=search&list=Vampire+Survivors+Official+Trailer',1794680,98.0,250000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Dave the Diver','dave-the-diver','MINTROCKET','MINTROCKET','2023-06-28','PC, PlayStation, Nintendo Switch','Adventure, RPG, Simulation','Single-player','T',1199,'Dive by day, run a sushi restaurant by night and uncover a humorous underwater mystery.','https://cdn.cloudflare.steamstatic.com/steam/apps/1868140/header.jpg','https://www.youtube.com/embed?listType=search&list=Dave+the+Diver+Official+Trailer',1868140,97.0,100000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('It Takes Two','it-takes-two','Hazelight Studios','Electronic Arts','2021-03-26','PC, PlayStation, Xbox, Nintendo Switch','Adventure, Co-op, Platformer','Multiplayer','T',1999,'A cooperative adventure built specifically for two players, with constantly changing mechanics and worlds.','https://cdn.cloudflare.steamstatic.com/steam/apps/1426210/header.jpg','https://www.youtube.com/embed?listType=search&list=It+Takes+Two+Official+Trailer',1426210,95.0,150000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('A Way Out','a-way-out','Hazelight Studios','Electronic Arts','2018-03-23','PC, PlayStation, Xbox','Adventure, Co-op, Action','Multiplayer','M',999,'A two-player-only cinematic prison-break adventure where both players must cooperate.','https://cdn.cloudflare.steamstatic.com/steam/apps/1222700/header.jpg','https://www.youtube.com/embed?listType=search&list=A+Way+Out+Official+Trailer',1222700,91.0,80000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Lies of P','lies-of-p','NEOWIZ','NEOWIZ','2023-09-18','PC, PlayStation, Xbox','Action, RPG, Soulslike','Single-player','M',2999,'A dark Belle Époque-inspired action RPG with precise combat, weapon combinations and a twisted Pinocchio story.','https://cdn.cloudflare.steamstatic.com/steam/apps/1627720/header.jpg','https://www.youtube.com/embed?listType=search&list=Lies+of+P+Official+Trailer',1627720,92.0,70000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('DOOM Eternal','doom-eternal','id Software','Bethesda Softworks','2020-03-19','PC, PlayStation, Xbox, Nintendo Switch','FPS, Action','Single-player, Multiplayer','M',1999,'Rip and tear through demons with fast movement, brutal weapons and aggressive arena combat.','https://cdn.cloudflare.steamstatic.com/steam/apps/782330/header.jpg','https://www.youtube.com/embed?listType=search&list=DOOM+Eternal+Official+Trailer',782330,93.0,200000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Cyberpunk 2077: Phantom Liberty','cyberpunk-phantom-liberty','CD PROJEKT RED','CD PROJEKT RED','2023-09-26','PC, PlayStation, Xbox','RPG, Action, Open World','Single-player','M',1999,'A major story expansion adding a new district, spy-thriller storyline and new gameplay systems.','https://cdn.cloudflare.steamstatic.com/steam/apps/2138330/header.jpg','https://www.youtube.com/embed?listType=search&list=Phantom+Liberty+Official+Trailer',2138330,94.0,30000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Assassin’s Creed Shadows','assassins-creed-shadows','Ubisoft Quebec','Ubisoft','2025-03-20','PC, PlayStation, Xbox','Action, Adventure, Open World','Single-player','M',4999,'Explore feudal Japan through two protagonists with different combat and stealth approaches.','https://cdn.cloudflare.steamstatic.com/steam/apps/3159330/header.jpg','https://www.youtube.com/embed?listType=search&list=Assassins+Creed+Shadows+Official+Trailer',3159330,76.0,10000,'Steam',0);

INSERT INTO gamematch_catalog_bootstrap_31 (title,slug,developer,publisher,release_date,platforms,genres,game_mode,age_rating,price,description,cover_image,trailer_url,steam_app_id,store_rating,rating_count,rating_source,featured) VALUES ('Black Myth: Wukong','black-myth-wukong','Game Science','Game Science','2024-08-20','PC, PlayStation','Action, RPG','Single-player','M',2999,'A visually rich action RPG inspired by Journey to the West, featuring staff combat, bosses and transformations.','https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg','https://www.youtube.com/embed?listType=search&list=Black+Myth+Wukong+Official+Trailer',2358720,95.0,300000,'Steam',0);


UPDATE games g
JOIN gamematch_catalog_bootstrap_31 s
  ON (s.steam_app_id IS NOT NULL AND g.steam_app_id = s.steam_app_id)
  OR LOWER(g.title) = LOWER(s.title)
SET
  g.name = s.title,
  g.title = s.title,
  g.slug = s.slug,
  g.developer = COALESCE(s.developer, g.developer),
  g.publisher = COALESCE(s.publisher, g.publisher),
  g.release_date = COALESCE(s.release_date, g.release_date),
  g.genre = s.genres,
  g.platform = s.platforms,
  g.mode = s.game_mode,
  g.platforms = s.platforms,
  g.genres = s.genres,
  g.game_mode = s.game_mode,
  g.age_rating = s.age_rating,
  g.description = s.description,
  g.image_url = s.cover_image,
  g.cover_image = s.cover_image,
  g.trailer_url = s.trailer_url,
  g.steam_app_id = COALESCE(s.steam_app_id, g.steam_app_id),
  g.source = CASE WHEN s.steam_app_id IS NULL THEN 'seed' ELSE g.source END,
  g.external_id = COALESCE(s.steam_app_id, g.external_id),
  g.store_rating = COALESCE(g.store_rating, s.store_rating),
  g.rating_count = CASE WHEN COALESCE(g.rating_count,0)=0 THEN s.rating_count ELSE g.rating_count END,
  g.rating_source = COALESCE(g.rating_source, s.rating_source),
  g.featured = s.featured;



INSERT INTO games
(name,title,slug,developer,publisher,release_date,genre,platform,mode,age_rating,price,
 description,image_url,cover_image,trailer_url,steam_app_id,source,external_id,
 store_rating,rating_count,rating_source,featured)
SELECT
 s.title,s.title,s.slug,s.developer,s.publisher,s.release_date,s.genres,s.platforms,s.game_mode,s.age_rating,s.price,
 s.description,s.cover_image,s.cover_image,s.trailer_url,s.steam_app_id,'seed',
 COALESCE(CAST(s.steam_app_id AS CHAR),s.slug),
 s.store_rating,s.rating_count,s.rating_source,s.featured
FROM gamematch_catalog_bootstrap_31 s
WHERE NOT EXISTS (
    SELECT 1 FROM games g
    WHERE LOWER(g.title)=LOWER(s.title)
       OR (s.steam_app_id IS NOT NULL AND g.steam_app_id=s.steam_app_id)
);


DROP TABLE gamematch_catalog_bootstrap_31;