<?php
function mobile_known_meta(string $slug): array { static $m = null; if ($m === null) $m = json_decode('{"garena-free-fire": {"rating": 86, "count": 124000000, "developer": "Garena", "publisher": "Garena", "release": "2017-12-04", "play": "https://play.google.com/store/apps/details?id=com.dts.freefireth"}, "free-fire-max": {"rating": 90, "count": 31800000, "developer": "Garena", "publisher": "Garena", "release": null, "play": "https://play.google.com/store/apps/details?id=com.dts.freefiremax"}, "call-of-duty-mobile": {"rating": 80, "count": 3840000, "developer": "Activision", "publisher": "Activision", "release": null, "play": "https://play.google.com/store/apps/details?id=com.garena.game.codm"}, "pubg-mobile": {"rating": 86, "count": 47300000, "developer": "Level Infinite", "publisher": "KRAFTON", "release": null, "play": "https://play.google.com/store/apps/details?id=com.tencent.ig"}, "mobile-legends-bang-bang": {"rating": 94, "count": 37700000, "developer": "MOONTON", "publisher": "MOONTON", "release": null, "play": "https://play.google.com/store/apps/details?id=com.mobile.legends"}, "clash-of-clans": {"rating": 90, "count": 55500000, "developer": "Supercell", "publisher": "Supercell", "release": null, "play": "https://play.google.com/store/apps/details?id=com.supercell.clashofclans"}, "subway-surfers": {"rating": 92, "count": 37200000, "developer": "SYBO Games", "publisher": "SYBO Games", "release": null, "play": "https://play.google.com/store/apps/details?id=com.kiloo.subwaysurf"}, "asphalt-9-legends": {"rating": 88, "count": 2740000, "developer": "Gameloft", "publisher": "Gameloft", "release": null, "play": "https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM"}, "brawl-stars": {"rating": 84, "count": 22500000, "developer": "Supercell", "publisher": "Supercell", "release": null, "play": "https://play.google.com/store/apps/details?id=com.supercell.brawlstars"}, "genshin-impact": {"rating": 32, "count": 5000000, "developer": "COGNOSPHERE PTE. LTD.", "publisher": "COGNOSPHERE PTE. LTD.", "release": null, "play": "https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact"}, "roblox": {"rating": 84, "count": 43000000, "developer": "Roblox Corporation", "publisher": "Roblox Corporation", "release": null, "play": "https://play.google.com/store/apps/details?id=com.roblox.client"}, "minecraft": {"rating": 86, "count": 4580000, "developer": "Mojang", "publisher": "Microsoft Corporation", "release": null, "play": "https://play.google.com/store/apps/details?id=com.mojang.minecraftpe"}, "pokemon-go": {"rating": 70, "count": 14600000, "developer": "Niantic", "publisher": "Scopely", "release": null, "play": "https://play.google.com/store/apps/details?id=com.nianticlabs.pokemongo"}}', true); return $m[$slug] ?? []; }
function mobile_asset_path(string $slug): string { $safe=preg_replace('/[^a-z0-9-]+/','-',strtolower($slug)); return 'images/covers/mobile-'.$safe.'.svg'; }
function asset_url(string $path): string { return preg_match('~^https?://~i',$path) ? $path : site_url($path); }
function ensure_mobile_catalog_data(PDO $pdo): void {
 static $done=false; if($done)return; $done=true;
 try {
  $rows=$pdo->query("SELECT id,title,slug,cover_image,platforms FROM games WHERE LOWER(platforms) LIKE '%mobile%'")->fetchAll();
  $up=$pdo->prepare("UPDATE games SET cover_image=CASE WHEN cover_image IS NULL OR cover_image='' OR cover_image LIKE '%game-placeholder.svg' THEN ? ELSE cover_image END, image_url=CASE WHEN image_url IS NULL OR image_url='' OR image_url LIKE '%game-placeholder.svg' THEN ? ELSE image_url END, developer=COALESCE(NULLIF(developer,''),?), publisher=COALESCE(NULLIF(publisher,''),?), release_date=COALESCE(release_date,?), store_rating=CASE WHEN (store_rating IS NULL OR store_rating=0) AND ? IS NOT NULL THEN ? ELSE store_rating END, rating_count=CASE WHEN (rating_count IS NULL OR rating_count=0) AND ? IS NOT NULL THEN ? ELSE rating_count END, rating_source=CASE WHEN ? IS NOT NULL THEN 'Google Play' ELSE rating_source END WHERE id=?");
  $offer=$pdo->prepare("INSERT INTO store_offers (game_id,store_name,platform,price,original_price,currency,url,is_official,source,external_id,is_available,last_checked_at) SELECT ?,?,?,?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM store_offers WHERE game_id=? AND store_name=? AND source='mobile-store')");
  foreach($rows as $r){ $slug=(string)$r['slug']; $title=(string)$r['title']; $m=mobile_known_meta($slug); $cover=mobile_asset_path($slug); $rating=$m['rating']??null; $count=$m['count']??null; $up->execute([$cover,$cover,$m['developer']??null,$m['publisher']??null,$m['release']??null,$rating,$rating,$count,$count,$rating,(int)$r['id']]); $play=$m['play']??('https://play.google.com/store/search?q='.rawurlencode($title).'&c=apps'); $ios='https://apps.apple.com/in/search?term='.rawurlencode($title); $offer->execute([(int)$r['id'],'Google Play','Mobile',0,0,'INR',$play,1,'mobile-store',$slug.'-android',(int)$r['id'],'Google Play']); $offer->execute([(int)$r['id'],'App Store','Mobile',0,0,'INR',$ios,1,'mobile-store',$slug.'-ios',(int)$r['id'],'App Store']); }
 } catch(Throwable $e) {}
}
